import ProductLandingV3Client from './ProductLandingV3Client';

// Landing data generated by scripts/build-product-landings.mjs — imported
// statically (not via dynamic import(variable)) so there is no webpack context
// chunk to flake on. This is a server component, so pulling in all landings
// only affects the server module graph, never the client bundle; a single
// product's HTML is what actually renders.
import assistant from './_landings/assistant.json';
import dashboards from './_landings/dashboards.json';
import forms from './_landings/forms.json';
import geo from './_landings/geo.json';
import growthDoctor from './_landings/growth-doctor.json';
import marketingOps from './_landings/marketing-ops.json';
import meeting from './_landings/meeting.json';
import reputation from './_landings/reputation.json';
import sdr from './_landings/sdr.json';
import shop from './_landings/shop.json';
import storeMaintenance from './_landings/store-maintenance.json';
import websiteMaintenance from './_landings/website-maintenance.json';
import whatsapp from './_landings/whatsapp.json';

type Landing = { css: string; html: string; js: string };

const LANDINGS: Record<string, Landing> = {
  assistant,
  dashboards,
  forms,
  geo,
  'growth-doctor': growthDoctor,
  'marketing-ops': marketingOps,
  meeting,
  reputation,
  sdr,
  shop,
  'store-maintenance': storeMaintenance,
  'website-maintenance': websiteMaintenance,
  whatsapp,
};

/**
 * Renders a product's landing design as REAL server-side DOM (no iframe).
 *
 * The design lives in public/_mock/<slug>-landing.html as a standalone document.
 * scripts/build-product-landings.mjs transforms each into app/products/_landings/
 * <slug>.json = { css, html, js }, where the CSS is namespaced under `#plv3` so
 * the mock's global resets can't collide with the site. We inline the scoped CSS
 * and the body HTML here (server-rendered => visible to users and crawlers), and
 * hand the interaction JS to a small client runner.
 *
 * This replaced ProductLandingV2, which iframed /_mock/<slug>-landing.html — a
 * path that 404s in production, so every product page rendered empty.
 */
export default function ProductLandingV3({ slug }: { slug: string }) {
  const data = LANDINGS[slug];
  if (!data) return null;

  return (
    <>
      {/* Fonts the landing designs rely on (Heebo body, Rubik headings). */}
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700;800;900&family=Rubik:wght@500;600;700;800&display=swap"
      />
      <style dangerouslySetInnerHTML={{ __html: data.css }} />
      <div id="plv3" className="plv3" dangerouslySetInnerHTML={{ __html: data.html }} />
      <ProductLandingV3Client js={data.js} />
    </>
  );
}
